//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackTrainCompanyEntities : DbContext
    {
        public HackTrainCompanyEntities()
            : base("name=HackTrainCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitySet> CitySet { get; set; }
        public virtual DbSet<CityStopsSet> CityStopsSet { get; set; }
        public virtual DbSet<DiscountCardSet> DiscountCardSet { get; set; }
        public virtual DbSet<ScheduleSet> ScheduleSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TicketSet> TicketSet { get; set; }
        public virtual DbSet<TrainSet> TrainSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
    }
}
