//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketSystemContainer : DbContext
    {
        public TicketSystemContainer()
            : base("name=TicketSystemContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<Tain> TainSet { get; set; }
        public virtual DbSet<Schedule> ScheduleSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Ticket> TicketSet { get; set; }
        public virtual DbSet<DiscountCard> DiscountCardSet { get; set; }
    }
}
