//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime TripDateAndTime { get; set; }
        public int OriginlaPrice { get; set; }
        public int PriceSold { get; set; }
        public Nullable<int> UserSoldTo { get; set; }
        public int SeatNumber { get; set; }
        public bool Bought { get; set; }
        public int OriginalPrice { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}
