//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrainCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCardSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountCardSet()
        {
            this.UserSet = new HashSet<UserSet>();
        }
    
        public long Id { get; set; }
        public string Type { get; set; }
        public int Discount { get; set; }
        public bool FirstClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSet { get; set; }
    }
}
