//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrainCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleSet()
        {
            this.CityStopsSet = new HashSet<CityStopsSet>();
        }
    
        public int Id { get; set; }
        public int TravelTime { get; set; }
        public int TrainId { get; set; }
        public int TicketId { get; set; }
        public int StartCityId { get; set; }
        public int EndCityId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual CitySet CitySet { get; set; }
        public virtual CitySet CitySet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CityStopsSet> CityStopsSet { get; set; }
        public virtual TicketSet TicketSet { get; set; }
        public virtual TrainSet TrainSet { get; set; }
    }
}
