//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrainCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketSet()
        {
            this.ScheduleSet = new HashSet<ScheduleSet>();
        }
    
        public int Id { get; set; }
        public System.DateTime TripDateAndTime { get; set; }
        public int OriginalPrice { get; set; }
        public int PriceSold { get; set; }
        public int UserSoldTo { get; set; }
        public int SeatNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleSet> ScheduleSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
