//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackTrainCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSet()
        {
            this.TicketSet = new HashSet<TicketSet>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string CreditCardNumberHash { get; set; }
        public string Address { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> DiscountCardId { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual DiscountCardSet DiscountCardSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSet> TicketSet { get; set; }
    }
}
